'use client';

import { useState } from 'react';
import { Download, FileText, Table, BarChart3, Share2 } from 'lucide-react';
import Papa from 'papaparse';
import { BitcoinPurchase, PortfolioMetrics } from '@/lib/types';
import { calculateDCAPerformance } from '@/lib/portfolio-calculator';

interface DataExportProps {
  purchases: BitcoinPurchase[];
  metrics: PortfolioMetrics;
  currentBTCPrice: number;
}

type ExportFormat = 'csv' | 'json' | 'summary';

export default function DataExport({ purchases, metrics, currentBTCPrice }: DataExportProps) {
  const [isExporting, setIsExporting] = useState(false);
  const [exportFormat, setExportFormat] = useState<ExportFormat>('csv');

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
    }).format(amount);
  };

  const generateCSVData = () => {
    const performance = calculateDCAPerformance(purchases, currentBTCPrice);
    
    return performance?.map((point, index) => ({
      purchase_number: index + 1,
      date: point.date,
      btc_purchased: purchases[index].amount_btc,
      purchase_price: purchases[index].price_usd,
      purchase_cost: purchases[index].amount_btc * purchases[index].price_usd,
      fees: purchases[index].fee_usd,
      exchange: purchases[index].exchange || '',
      running_btc_total: point.runningBTC,
      running_invested_total: point.runningInvested,
      avg_cost_basis: point.avgCostBasis,
      current_btc_price: currentBTCPrice,
      portfolio_value: point.currentValue,
      unrealized_pnl: point.unrealizedPnL,
      unrealized_pnl_percent: point.unrealizedPnLPercent,
      notes: purchases[index].notes || ''
    })) || [];
  };

  const generateJSONData = () => {
    const performance = calculateDCAPerformance(purchases, currentBTCPrice);
    
    return {
      metadata: {
        export_date: new Date().toISOString(),
        total_purchases: purchases.length,
        date_range: {
          first_purchase: metrics.firstPurchaseDate,
          last_purchase: metrics.lastPurchaseDate
        },
        current_btc_price: currentBTCPrice
      },
      summary: metrics,
      purchases: purchases,
      performance_history: performance
    };
  };

  const generateSummaryReport = () => {
    const daysSinceFirst = Math.floor(
      (new Date().getTime() - new Date(metrics.firstPurchaseDate).getTime()) / (1000 * 60 * 60 * 24)
    );
    
    return `BITCOIN DCA PORTFOLIO SUMMARY REPORT
Generated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}

====================================
PORTFOLIO OVERVIEW
====================================
Total Bitcoin Holdings: ₿${metrics.totalBTC.toFixed(8)}
Current Portfolio Value: ${formatCurrency(metrics.currentValue)}
Total Amount Invested: ${formatCurrency(metrics.totalInvested)}
Total Fees Paid: ${formatCurrency(metrics.totalFees)}

Average Cost Basis: ${formatCurrency(metrics.averageCostBasis)}
Current Bitcoin Price: ${formatCurrency(currentBTCPrice)}

Unrealized P&L: ${formatCurrency(metrics.unrealizedPnL)} (${metrics.unrealizedPnLPercent.toFixed(2)}%)

====================================
INVESTMENT STATISTICS
====================================
Number of Purchases: ${metrics.purchaseCount}
Investment Period: ${daysSinceFirst} days
First Purchase: ${new Date(metrics.firstPurchaseDate).toLocaleDateString()}
Last Purchase: ${new Date(metrics.lastPurchaseDate).toLocaleDateString()}

Average Purchase Amount: ${formatCurrency(metrics.totalInvested / metrics.purchaseCount)}
Average Days Between Purchases: ${(daysSinceFirst / metrics.purchaseCount).toFixed(1)}

Fee Efficiency: ${((metrics.totalFees / metrics.totalInvested) * 100).toFixed(2)}% of total investment

====================================
RECENT PURCHASES (Last 5)
====================================
${purchases.slice(-5).reverse().map((p, i) => 
`${new Date(p.date).toLocaleDateString()}: ₿${p.amount_btc.toFixed(8)} at ${formatCurrency(p.price_usd)} (${p.exchange || 'Unknown'})`
).join('\n')}

====================================
DISCLAIMER
====================================
This report is for informational purposes only and should not be considered financial advice.
Data is processed locally in your browser for privacy protection.
Past performance does not guarantee future results.

Report generated by Bitcoin DCA Tracker
https://your-domain.com
`;
  };

  const handleExport = async () => {
    setIsExporting(true);
    
    try {
      let content: string;
      let filename: string;
      let mimeType: string;

      switch (exportFormat) {
        case 'csv':
          const csvData = generateCSVData();
          content = Papa.unparse(csvData);
          filename = `bitcoin-dca-portfolio-${new Date().toISOString().split('T')[0]}.csv`;
          mimeType = 'text/csv';
          break;
          
        case 'json':
          const jsonData = generateJSONData();
          content = JSON.stringify(jsonData, null, 2);
          filename = `bitcoin-dca-portfolio-${new Date().toISOString().split('T')[0]}.json`;
          mimeType = 'application/json';
          break;
          
        case 'summary':
          content = generateSummaryReport();
          filename = `bitcoin-dca-summary-${new Date().toISOString().split('T')[0]}.txt`;
          mimeType = 'text/plain';
          break;
          
        default:
          throw new Error('Invalid export format');
      }

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
    } catch (error) {
      console.error('Export failed:', error);
      alert('Export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  const sharePortfolio = async () => {
    const summaryText = `My Bitcoin DCA Portfolio:
₿${metrics.totalBTC.toFixed(4)} BTC
${formatCurrency(metrics.currentValue)} current value
${formatCurrency(metrics.unrealizedPnL)} P&L (${metrics.unrealizedPnLPercent.toFixed(1)}%)
${metrics.purchaseCount} purchases over ${Math.floor((new Date().getTime() - new Date(metrics.firstPurchaseDate).getTime()) / (1000 * 60 * 60 * 24))} days

#Bitcoin #DCA #HODL`;

    if (navigator.share) {
      try {
        await navigator.share({
          title: 'My Bitcoin DCA Portfolio',
          text: summaryText,
        });
      } catch (error) {
        // Fallback to clipboard
        navigator.clipboard.writeText(summaryText);
        alert('Portfolio summary copied to clipboard!');
      }
    } else {
      navigator.clipboard.writeText(summaryText);
      alert('Portfolio summary copied to clipboard!');
    }
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-sm p-6">
      <div className="flex items-center justify-between mb-6">
        <h3 className="text-lg font-medium text-gray-900 dark:text-white">Export Portfolio Data</h3>
        <button
          onClick={sharePortfolio}
          className="flex items-center px-3 py-2 text-sm bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
        >
          <Share2 className="w-4 h-4 mr-2" />
          Share
        </button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
        <button
          onClick={() => setExportFormat('csv')}
          className={`p-4 border-2 rounded-lg transition-colors ${
            exportFormat === 'csv'
              ? 'border-orange-500 bg-orange-50 dark:bg-orange-950/20'
              : 'border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600'
          }`}
        >
          <Table className="w-8 h-8 text-orange-600 dark:text-orange-400 mx-auto mb-2" />
          <h4 className="font-medium text-gray-900 dark:text-white mb-1">CSV Export</h4>
          <p className="text-sm text-gray-600 dark:text-gray-300">
            Detailed spreadsheet with purchase history and performance data
          </p>
        </button>

        <button
          onClick={() => setExportFormat('json')}
          className={`p-4 border-2 rounded-lg transition-colors ${
            exportFormat === 'json'
              ? 'border-orange-500 bg-orange-50 dark:bg-orange-950/20'
              : 'border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600'
          }`}
        >
          <BarChart3 className="w-8 h-8 text-orange-600 dark:text-orange-400 mx-auto mb-2" />
          <h4 className="font-medium text-gray-900 dark:text-white mb-1">JSON Export</h4>
          <p className="text-sm text-gray-600 dark:text-gray-300">
            Complete data structure for developers and advanced analysis
          </p>
        </button>

        <button
          onClick={() => setExportFormat('summary')}
          className={`p-4 border-2 rounded-lg transition-colors ${
            exportFormat === 'summary'
              ? 'border-orange-500 bg-orange-50 dark:bg-orange-950/20'
              : 'border-gray-200 dark:border-gray-700 hover:border-gray-300 dark:hover:border-gray-600'
          }`}
        >
          <FileText className="w-8 h-8 text-orange-600 dark:text-orange-400 mx-auto mb-2" />
          <h4 className="font-medium text-gray-900 dark:text-white mb-1">Summary Report</h4>
          <p className="text-sm text-gray-600 dark:text-gray-300">
            Human-readable portfolio summary and performance report
          </p>
        </button>
      </div>

      <div className="flex justify-center">
        <button
          onClick={handleExport}
          disabled={isExporting}
          className="flex items-center px-6 py-3 bg-orange-600 hover:bg-orange-700 disabled:bg-orange-400 text-white font-medium rounded-lg transition-colors"
        >
          {isExporting ? (
            <>
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-2"></div>
              Exporting...
            </>
          ) : (
            <>
              <Download className="w-4 h-4 mr-2" />
              Export {exportFormat.toUpperCase()}
            </>
          )}
        </button>
      </div>

      <div className="mt-4 text-xs text-gray-500 dark:text-gray-400 text-center">
        <p>All data processing happens locally in your browser. No data is sent to external servers.</p>
      </div>
    </div>
  );
}